import { Router } from "express";
import ordersController from "../controllers/orders.js";
import { passportCall } from "../middlewares/auth/passportCall.js";
import { strategies } from "../config/passport.js";
export const orderRouter = Router();
orderRouter.use(passportCall(strategies.JWT));
orderRouter.get("/", ordersController.getAll);
orderRouter.get("/:id", ordersController.getById);
orderRouter.get("/sale_id/:sale_id", ordersController.getOrdersByOrderNumber);
orderRouter.post("/", ordersController.create);
orderRouter.post("/mocks", ordersController.createMockedOrders);
orderRouter.put("/:id", ordersController.update);
orderRouter.delete("/:id", ordersController.deleteOrder);
