import { Router } from "express";
import salesController from "../controllers/sales.js";
import { passportCall } from "../middlewares/auth/passportCall.js";
import { strategies } from "../config/passport.js";
export const saleRouter = Router();
saleRouter.use(passportCall(strategies.JWT));
saleRouter.get("/", salesController.getAll);
saleRouter.post("/", salesController.create);
saleRouter.delete("/:id", salesController.deleteSale);
saleRouter.get("/monthlySales", salesController.getMonthlySales);
